package com.cleverbuilder.bookservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7.fuse-sb2-750026-redhat-00001
 * 2020-06-15T22:23:22.114+02:00
 * Generated source version: 3.2.7.fuse-sb2-750026-redhat-00001
 *
 */
@WebService(targetNamespace = "http://www.cleverbuilder.com/BookService/", name = "BookService")
@XmlSeeAlso({ObjectFactory.class})
public interface BookService {

    @WebMethod(operationName = "GetBook", action = "http://www.cleverbuilder.com/BookService/GetBook")
    @RequestWrapper(localName = "GetBook", targetNamespace = "http://www.cleverbuilder.com/BookService/", className = "com.cleverbuilder.bookservice.GetBook")
    @ResponseWrapper(localName = "GetBookResponse", targetNamespace = "http://www.cleverbuilder.com/BookService/", className = "com.cleverbuilder.bookservice.GetBookResponse")
    public void getBook(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ID", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> id,
        @WebParam(mode = WebParam.Mode.OUT, name = "Title", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> title,
        @WebParam(mode = WebParam.Mode.OUT, name = "Author", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> author
    );

    @WebMethod(operationName = "AddBook", action = "http://www.cleverbuilder.com/BookService/AddBook")
    @RequestWrapper(localName = "AddBook", targetNamespace = "http://www.cleverbuilder.com/BookService/", className = "com.cleverbuilder.bookservice.AddBook")
    @ResponseWrapper(localName = "AddBookResponse", targetNamespace = "http://www.cleverbuilder.com/BookService/", className = "com.cleverbuilder.bookservice.AddBookResponse")
    @WebResult(name = "ID", targetNamespace = "")
    public java.lang.String addBook(
        @WebParam(name = "Title", targetNamespace = "")
        java.lang.String title,
        @WebParam(name = "Author", targetNamespace = "")
        java.lang.String author
    );

    @WebMethod(operationName = "GetAllBooks", action = "http://www.cleverbuilder.com/BookService/GetAllBooks")
    @RequestWrapper(localName = "GetAllBooks", targetNamespace = "http://www.cleverbuilder.com/BookService/", className = "com.cleverbuilder.bookservice.GetAllBooks")
    @ResponseWrapper(localName = "GetAllBooksResponse", targetNamespace = "http://www.cleverbuilder.com/BookService/", className = "com.cleverbuilder.bookservice.GetAllBooksResponse")
    @WebResult(name = "Book", targetNamespace = "")
    public java.util.List<com.cleverbuilder.bookservice.GetAllBooksResponse.Book> getAllBooks();
}
