
package com.cleverbuilder.bookservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7.fuse-sb2-750026-redhat-00001
 * 2020-06-15T22:23:22.037+02:00
 * Generated source version: 3.2.7.fuse-sb2-750026-redhat-00001
 *
 */
public final class BookService_BookServiceSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.cleverbuilder.com/BookService/", "BookService");

    private BookService_BookServiceSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BookService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        BookService_Service ss = new BookService_Service(wsdlURL, SERVICE_NAME);
        BookService port = ss.getBookServiceSOAP();

        {
        System.out.println("Invoking getBook...");
        java.lang.String _getBook_idVal = "";
        javax.xml.ws.Holder<java.lang.String> _getBook_id = new javax.xml.ws.Holder<java.lang.String>(_getBook_idVal);
        javax.xml.ws.Holder<java.lang.String> _getBook_title = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _getBook_author = new javax.xml.ws.Holder<java.lang.String>();
        port.getBook(_getBook_id, _getBook_title, _getBook_author);

        System.out.println("getBook._getBook_id=" + _getBook_id.value);
        System.out.println("getBook._getBook_title=" + _getBook_title.value);
        System.out.println("getBook._getBook_author=" + _getBook_author.value);

        }
        {
        System.out.println("Invoking addBook...");
        java.lang.String _addBook_title = "";
        java.lang.String _addBook_author = "";
        java.lang.String _addBook__return = port.addBook(_addBook_title, _addBook_author);
        System.out.println("addBook.result=" + _addBook__return);


        }
        {
        System.out.println("Invoking getAllBooks...");
        java.util.List<com.cleverbuilder.bookservice.GetAllBooksResponse.Book> _getAllBooks__return = port.getAllBooks();
        System.out.println("getAllBooks.result=" + _getAllBooks__return);


        }

        System.exit(0);
    }

}
